apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  db_url: {{ printf "root:%s@tcp(db:%v)/cfsdb?serverVersion=5.7&charset=utf8mb4" .Values.secrets.db_root_psw .Values.db.port | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  root_psw: {{ .Values.secrets.db_root_psw | b64enc }}  